services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./shops:/app/shops
      - ./nginx:/app/nginx
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/data:/app/data
      - ./templates:/app/templates
    environment:
      - HOST_PROJECT_DIR=${PWD}
    env_file: .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    container_name: nginx-proxy
    restart: unless-stopped
    profiles:
      - proxy
