services:
  web:
    image: ghcr.io/lr-paris/shuttle:latest
    pull_policy: always
    ports:
      - "{PORT}:3000"
    volumes:
      - ./DATABASE:/app/DATABASE
      - ./orders:/app/orders
    environment:
      - SHOP_NAME={SHOP_NAME}
      - SHOP_SLUG={SHOP_SLUG}
      - SHOP_PORT={PORT}
    restart: unless-stopped
