services:
  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./DATABASE:/app
    ports:
      - "{PORT}:3000"
    command: sh -c "npm install && npm run build && npm start"
    restart: unless-stopped
